//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntity.Database
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public Customer()
        {
            this.SalesOrderHeaders = new HashSet<SalesOrderHeader>();
        }

        [DataMember]
        public int CustomerID { get; set; }
        [DataMember]
        public Nullable<int> PersonID { get; set; }
        [DataMember]
        public Nullable<int> StoreID { get; set; }
        [DataMember]
        public Nullable<int> TerritoryID { get; set; }
        [DataMember]
        public string AccountNumber { get; set; }
        [DataMember]
        public System.Guid rowguid { get; set; }
        [DataMember]
        public System.DateTime ModifiedDate { get; set; }

        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
      public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
    }
}
