//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntity.Database
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class SalesOrderDetail
    {
        [DataMember]
        public int SalesOrderID { get; set; }
        [DataMember]
        public int SalesOrderDetailID { get; set; }
        [DataMember]
        public string CarrierTrackingNumber { get; set; }
        [DataMember]
        public short OrderQty { get; set; }
        [DataMember]
        public int ProductID { get; set; }
        [DataMember]
        public int SpecialOfferID { get; set; }
        [DataMember]
        public decimal UnitPrice { get; set; }
        [DataMember]
        public decimal UnitPriceDiscount { get; set; }
        [DataMember]
        public decimal LineTotal { get; set; }
        [DataMember]
        public System.Guid rowguid { get; set; }
        [DataMember]
        public System.DateTime ModifiedDate { get; set; }


        public virtual SalesOrderHeader SalesOrderHeader { get; set; }
    }
}
